### ISSUE TITLE
Placing some address markers in the wrong place, pattern not clear

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/transport_bidding#5]
![image](https://cloud.githubusercontent.com/assets/2911176/11236208/d580c656-8e2b-11e5-945b-56cb645294bd.png)

**Comment by RohanM** [comment]
Deleted old transport cycles. Re-imported sample data. Markers appeared only in Victoria, Australia.

**Comment by kirstenalarsen** [comment]
just checked . . and now clicking on the rows doesn’t do anything to the map . . in fact I think that the TC7 data is not actually showing on the map at all . .

**Comment by RohanM** [comment]
I found a further problem (not geocoding the new addresses). Should be fixed now.

**Comment by kirstenalarsen** [comment]
ok!! now we are in business! you’re a star - looking good :)
