### ISSUE TITLE
Update table and field details

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/transport_bidding#9]
Table updates:
- Change "Product" to "Description"
- Remove "Qty"
- Add "Day" and "Time" (will need adding data field. Spec this.)
- Hide "Bid", "Bid value" and "Clear bids" button, bid form.

Update details pane:
- "Shipping instructions" to "Notes"
- "Destination address" to "Destination", and draw from distributor field, to get distributor name, not the address.
- "Source address" to "Source". Use field - supplier name, not address.
- Do not round quantity field.

**Comment by RohanM** [comment]
I've used a single field, `moving_at` for the day/time. I've split it out into two columns on the table on the home page.

**Comment by kirstenalarsen** [comment]
damn - sorry Rohan, should have made this clearer - day should be actual day, not date - as in Monday etc (as in the sample data) so probably just needs to be a text field . .

**Comment by RohanM** [comment]
Hmm, so just day, no time field? And it should draw from what used to be the quantity field in the CSV file?

**Comment by kirstenalarsen** [comment]
no, both . . a field for day (probably text) and a field for time - fine as you’ve done it :)

**Comment by RohanM** [comment]
Okay, I've updated that. Instead of using the quantity field, it uses two new fields at the end - moving day and moving time. There's examples in the dataX.csv files. I've set up all the data to https://transport-bidding-official.herokuapp.com .

**Comment by kirstenalarsen** [comment]
awesome. beautiful work rohan - looks like we have what we need for tomorrow :) thanks so much!!
